name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '1 2 5 * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'corretto'
    - uses: gradle/actions/setup-gradle@v4
    # See https://docs.gradle.org/current/userguide/logging.html#sec:choosing_a_log_level for the log levels
    # We opted for "-i", because it outputs the commands used to build the application image
    - run: ./gradlew -i jpackage
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: javafxreproducer-${{ matrix.os }}
        path: build/distributions
        compression-level: 0
